common:
    application:
        core:
            apt-transport-https: 2.7.14build2
            ca-certificates: "20240203"
            curl: 8.5.0-2ubuntu10.6
            gpg: 2.4.4-2ubuntu17.2
        external:
            - name: kubernetes
              gpg_key_url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
              repo: https://pkgs.k8s.io/core:/stable:/v1.32/deb/
              packages:
                kubeadm: 1.32.3-1.1
                kubectl: 1.32.3-1.1
                kubelet: 1.32.3-1.1
            - name: cri-o
              gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
              packages:
                cri-o: 1.32.1-1.1
    configuration:
        - name: haproxy
          template_file: ./config/template/haproxy_template.cfg
          output_file: ./config/output/haproxy.cfg
          remote_file: /etc/haproxy/haproxy.cfg
          sudo: true
          data:
            backends:
                - address: 192.168.0.101
                  name: lab-101
                  port: 16443
                - address: 192.168.0.102
                  name: lab-102
                  port: 16443
                - address: 192.168.0.103
                  name: lab-103
                  port: 16443
        - name: check_apiserver
          template_file: ./config/template/check_apiserver_template.sh
          output_file: ./config/output/check_apiserver.sh
          remote_file: /etc/keepalived/check_apiserver.sh
          sudo: true
          data:
            port: 16443
        - name: keepalived_manifest
          template_file: ./config/template/keepalived_manifest.yaml
          output_file: ./config/output/keepalived_manifest.yaml
          remote_file: /etc/kubernetes/manifests/keepalived.yaml
          sudo: true
          data: null
        - name: haproxy_manifest
          template_file: ./config/template/haproxy_manifest.yaml
          output_file: ./config/output/haproxy_manifest.yaml
          remote_file: /etc/kubernetes/manifests/haproxy.yaml
          sudo: true
          data:
            port: 16443
    command:
        - name: crio
          command: systemctl start crio.service
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: swapoff -a
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: modprobe br_netfilter
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: sysctl -w net.ipv4.ip_forward=1
          expected_output: ""
          sudo: true
hosts:
    - host: localhost
      port: "2022"
      user: lab
      password: lab
      application:
        core:
            nginx: 1.24.0-2ubuntu7.3
            vim: 2:9.1.0016-1ubuntu7.8
        external:
            - name: cri-o
              gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
              packages:
                cri-o: 1.32.1-1.1
      configuration:
        - name: keepalived
          template_file: ./config/template/keepalived_template.cfg
          output_file: ./config/output/keepalived_node101.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          data:
            interface: eth0
            priority: 100
            state: MASTER
            virtual_ip: 192.168.0.100
        - name: kubelet
          template_file: ./config/template/kubelet_template
          output_file: ./config/output/kubelet-101
          remote_file: /etc/default/kubelet
          sudo: true
          data:
            ip: 192.168.0.101
      command: []
    - host: localhost
      port: "2122"
      user: lab
      password: lab
      application:
        core:
            nginx: 1.24.0-2ubuntu7.3
            vim: 2:9.1.0016-1ubuntu7.8
        external: []
      configuration:
        - name: keepalived
          template_file: ./config/template/keepalived_template.cfg
          output_file: ./config/output/keepalived_node102.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          data:
            interface: eth0
            priority: 110
            state: BACKUP
            virtual_ip: 192.168.0.100
        - name: kubelet
          template_file: ./config/template/kubelet_template
          output_file: ./config/output/kubelet-102
          remote_file: /etc/default/kubelet
          sudo: true
          data:
            ip: 192.168.0.102
      command: []
    - host: localhost
      port: "2222"
      user: lab
      password: lab
      applcation:
        core:
            nginx: 1.24.0-2ubuntu7.3
            vim: 2:9.1.0016-1ubuntu7.8
        external: []
      configuration:
        - name: keepalived
          template_file: ./config/template/keepalived_template.cfg
          output_file: ./config/output/keepalived_node103.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          data:
            interface: eth0
            priority: 110
            state: BACKUP
            virtual_ip: 192.168.0.100
        - name: kubelet
          template_file: ./config/template/kubelet_template
          output_file: ./config/output/kubelet-103
          remote_file: /etc/default/kubelet
          sudo: true
          data:
            ip: 192.168.0.103
      command: []