common:
    packages:
        standard:
            - apt-transport-https
            - ca-certificates
            - curl
            - gpg
        third_party:
            - gpg_key_url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
              name: kubernetes
              packages:
                - kubeadm
                - kubelet
                - kubectl
              repo: https://pkgs.k8s.io/core:/stable:/v1.32/deb/
            - gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              name: cri-o
              packages:
                - cri-o
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
    templates:
        - data:
            backends:
                - address: 192.168.0.101
                  name: lab-101
                  port: 16443
                - address: 192.168.0.102
                  name: lab-102
                  port: 16443
                - address: 192.168.0.103
                  name: lab-103
                  port: 16443
          name: haproxy
          output_file: ./config/output/haproxy.cfg
          remote_file: /etc/haproxy/haproxy.cfg
          sudo: true
          template_file: ./config/template/haproxy_template.cfg
        - data:
            port: 16443
          name: check_apiserver
          output_file: ./config/output/check_apiserver.sh
          remote_file: /etc/keepalived/check_apiserver.sh
          sudo: true
          template_file: ./config/template/check_apiserver_template.sh
        - name: keepalived_manifest
          output_file: ./config/output/keepalived_manifest.yaml
          remote_file: /etc/kubernetes/manifests/keepalived.yaml
          sudo: true
          template_file: ./config/template/keepalived_manifest.yaml
        - data:
            port: 16443
          name: haproxy_manifest
          output_file: ./config/output/haproxy_manifest.yaml
          remote_file: /etc/kubernetes/manifests/haproxy.yaml
          sudo: true
          template_file: ./config/template/haproxy_manifest.yaml
    custom_procedures:
        - name: crio
          command: "systemctl start crio.service"
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: "swapoff -a"
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: "modprobe br_netfilter"
          expected_output: ""
          sudo: true
        - name: install_k8s
          command: "sysctl -w net.ipv4.ip_forward=1"
          expected_output: ""
          sudo: true

hosts:
    # - host: 192.168.100.14
    #   packages:
    #     standard:
    #         - nginx
    #     third_party:
    #         - gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
    #           name: cri-o
    #           packages:
    #             - cri-o
    #           repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
    #   password: admin
    #   templates:
    #     - data:
    #         interface: eth0
    #         priority: 100
    #         state: MASTER
    #         virtual_ip: 172.18.149.100
    #       name: keepalived
    #       output_file: ./config/output/keepalived.cfg
    #       remote_file: /etc/keepalived/keepalived.conf
    #       sudo: true
    #       template_file: ./config/template/keepalived_template.cfg
    #   user: admin
    # - host: 192.168.100.106
    - host: localhost
      port: 2022
      packages:
        standard:
            - nginx
            - vim
        third_party:
            - gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              name: cri-o
              packages:
                - cri-o
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
      password: lab
      templates:
        - data:
            interface: eth0
            priority: 100
            state: MASTER
            virtual_ip: 192.168.0.100
          name: keepalived
          output_file: ./config/output/keepalived.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          template_file: ./config/template/keepalived_template.cfg
        - name: kubelet
          data:
            ip: 192.168.0.101
          output_file: ./config/output/kubelet-101
          remote_file: /etc/default/kubelet
          sudo: true
          template_file: ./config/template/kubelet_template
      user: lab
    - host: localhost
      port: 2122
      packages:
        standard:
            - nginx
            - vim
        third_party:
            - gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              name: cri-o
              packages:
                - cri-o
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
      password: lab
      templates:
        - data:
            interface: eth0
            priority: 110
            state: BACKUP
            virtual_ip: 192.168.0.100
          name: keepalived
          output_file: ./config/output/keepalived.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          template_file: ./config/template/keepalived_template.cfg
        - name: kubelet
          data:
            ip: 192.168.0.102
          output_file: ./config/output/kubelet-102
          remote_file: /etc/default/kubelet
          sudo: true
          template_file: ./config/template/kubelet_template
      user: lab
    - host: localhost
      port: 2222
      packages:
        standard:
            - nginx
            - vim
        third_party:
            - gpg_key_url: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/Release.key
              name: cri-o
              packages:
                - cri-o
              repo: https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.32/deb/
      password: lab
      templates:
        - data:
            interface: eth0
            priority: 110
            state: BACKUP
            virtual_ip: 192.168.0.100
          name: keepalived
          output_file: ./config/output/keepalived.cfg
          remote_file: /etc/keepalived/keepalived.conf
          sudo: true
          template_file: ./config/template/keepalived_template.cfg
        - name: kubelet
          data:
            ip: 192.168.0.103
          output_file: ./config/output/kubelet-103
          remote_file: /etc/default/kubelet
          sudo: true
          template_file: ./config/template/kubelet_template
      user: lab